[theme]
base = "dark"
primaryColor = "#E84343"
backgroundColor = "#0B0D10"
secondaryBackgroundColor = "#14171C"
textColor = "#E5E7EB"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
enableStaticServing = true