[theme]
base = "light"
primaryColor = "#E84343"
backgroundColor = "#F4F6F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1F2937"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true